<template>
  <!-- Background layer (R070, UAT F3) — a CSS background rather than an
       <img>: a URL that fails to load simply paints nothing, leaving the
       root's own black background and every word on the slide intact,
       with no error state to build and no way for a broken image to
       blank a slide mid-service. Inline negative z-index, not a Tailwind
       utility, so the layering never depends on whether that utility is
       generated by this project's Tailwind config. `suppressBackground`
       (Phase 90/94) forces this null regardless of the slide's own
       resolved url — the confidence monitor renders black-only.
       PresentationViewer's viewer root is already a stacking context
       (fixed inset-0 z-50), and this is emitted as a sibling ROOT node
       here so it stays a direct child of that root when composed. -->
  <div
    v-if="currentBackgroundUrl"
    data-testid="presentation-background"
    class="absolute inset-0 bg-cover bg-center"
    :style="{ backgroundImage: `url(${currentBackgroundUrl})`, zIndex: -1 }"
  ></div>
  <div
    v-if="currentBackgroundUrl"
    data-testid="presentation-background-scrim"
    class="absolute inset-0 bg-black/50"
    :style="{ zIndex: -1 }"
  ></div>

  <!-- Slide content — PresentationViewer keeps the v-else-if="currentSlide"
       guard around the <SlideCanvas> element itself; here the block renders
       whenever props.slide is non-null. -->
  <div
    v-if="props.slide"
    data-testid="presentation-slide"
    class="w-full h-full flex flex-col items-center justify-center px-16 py-12 text-center"
  >
    <!-- Render-pending — the FIRST branch of this chain (R080/D-15).
         Occupies the slide's normal position; never filters it out of
         props.slides, hasSlides, atFirst, atLast or progressLabel. -->
    <div
      v-if="currentRenderState === 'pending'"
      data-testid="presentation-render-pending"
      class="flex flex-col items-center gap-4"
    >
      <svg
        class="h-10 w-10 animate-spin text-indigo-400"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        aria-hidden="true"
      >
        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"></path>
      </svg>
      <h2 class="text-4xl font-semibold text-gray-100">This slide is still rendering.</h2>
    </div>

    <!-- Render-failed — amber, never red (discretionary decision,
         42-UI-SPEC.md § Color): a congregation-facing pause, not an error
         page. Same layout family and same heading size/weight as pending
         above — never visually louder. -->
    <div
      v-else-if="currentRenderState === 'failed'"
      data-testid="presentation-render-failed"
      class="flex flex-col items-center gap-4"
    >
      <svg
        class="h-8 w-8 text-amber-300"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        aria-hidden="true"
      >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
      </svg>
      <h2 class="text-4xl font-semibold text-gray-100">This slide couldn't be rendered.</h2>
      <p class="text-[13px] leading-normal text-gray-400">{{ currentRenderFailureSentence }}</p>
    </div>

    <!-- lyric -->
    <template v-else-if="slideKind === 'lyric'">
      <p
        data-testid="presentation-body"
        class="text-gray-100 whitespace-pre-line text-5xl font-normal leading-[1.4]"
      >
        {{ (props.slide.slide as LyricSlide).lines.join('\n') }}
      </p>
    </template>

    <!-- copyright -->
    <template v-else-if="slideKind === 'copyright'">
      <p
        data-testid="presentation-body"
        class="text-6xl font-semibold leading-[1.15] text-gray-100"
      >
        {{ (props.slide.slide as CopyrightSlide).title }}
      </p>
      <p class="text-2xl font-semibold leading-[1.3] text-gray-300 mt-4 presentation-copyright-authors">
        {{ (props.slide.slide as CopyrightSlide).authors.join(', ') }}
      </p>
      <div
        data-testid="presentation-copyright-fine-print"
        class="text-xs text-gray-500 leading-[1.4] mt-8"
      >
        <p v-for="(line, idx) in (props.slide.slide as CopyrightSlide).copyrightLines" :key="idx">{{ line }}</p>
        <p>CCLI Song #{{ (props.slide.slide as CopyrightSlide).ccliSongNumber }}</p>
        <p>CCLI License #{{ (props.slide.slide as CopyrightSlide).ccliLicenseNumber }}</p>
      </div>
    </template>

    <!-- scripture -->
    <template v-else-if="slideKind === 'scripture'">
      <!--
        D1: for a Reference-state (non-congregational) slide, the
        reference always renders unconditionally — the assembler builds
        reference-only scripture slides with an empty passage string, so
        this is frequently the slide's ENTIRE visible content.

        R105 (Phase 49): for a congregational reading, the reference now
        has its OWN dedicated slide (a Reference-state slide, itself
        `!isCongregational`), so it renders on NO congregational section
        slide — the gate is simply `!isCongregational`. Either way, the
        paragraph carries the same body treatment as every other kind,
        with no size/weight step against the passage below.
      -->
      <p
        v-if="!isCongregational"
        data-testid="presentation-scripture-reference"
        class="text-gray-100 whitespace-pre-line text-5xl font-normal leading-[1.4] mb-8"
      >
        {{ (props.slide.slide as ScriptureSlide).reference }}
      </p>
      <template v-if="isCongregational">
        <!--
          38-02: one slide carries exactly one section — the speaker sits
          on its own line above the section's words, at the same SIZE and
          WEIGHT as the reference above them and the passage below (no
          size/weight step). There is nothing left to distinguish between
          stacked sections, because there is no longer a stack.

          Owner follow-up (2026-08-05): the speaker line gets COLOUR back,
          and only colour — the passage text itself stays text-gray-100 —
          the words are not colour-coded, only the speaker naming them.
        -->
        <p
          data-testid="presentation-speaker"
          class="text-5xl font-normal leading-[1.4] mb-2"
          :class="speakerColorClass"
        >
          {{ speakerLabelText }}
        </p>
        <p
          data-testid="presentation-congregational-section"
          class="text-gray-100 whitespace-pre-line text-5xl font-normal leading-[1.4]"
        >
          {{ ((props.slide.slide as ScriptureSlide).section as CongregationalSection).text }}
        </p>
      </template>
      <p
        v-else
        data-testid="presentation-body"
        class="text-gray-100 whitespace-pre-line text-5xl font-normal leading-[1.4]"
      >
        {{ (props.slide.slide as ScriptureSlide).text }}
      </p>
    </template>

    <!-- text -->
    <template v-else-if="slideKind === 'text'">
      <p
        data-testid="presentation-body"
        class="text-gray-100 whitespace-pre-line text-5xl font-normal leading-[1.4]"
      >
        {{ (props.slide.slide as TextSlide).body }}
      </p>
    </template>

    <!-- image -->
    <template v-else-if="slideKind === 'image'">
      <img
        data-testid="presentation-image"
        :src="(props.slide.slide as ImageSlide).imageUrl"
        :alt="(props.slide.slide as ImageSlide).altText ?? ''"
        class="max-h-[80vh] max-w-full object-contain"
      />
    </template>

    <!-- blackout (R303, Phase 105) — renders NOTHING: no text, no label, no
         background image. The parent root's own bg-black (Audience/
         Confidence/PresentationViewer all already paint one) is the entire
         visible result; this marker exists only so a test/DOM inspector can
         confirm the branch was taken, not to draw anything itself. -->
    <div
      v-else-if="slideKind === 'blackout'"
      data-testid="presentation-blackout"
      aria-hidden="true"
    ></div>

    <!-- Video slide's own source (D-17/D-18) — chromeless, imperatively
         driven, reusing the same videoRef/play/pause/error/autoplay-blocked
         wiring the pre-D-18 bed video used. A video slide has no separate
         per-kind template branch above: video is slide-only (never a bed),
         so this is the video slide's entire visual content — nothing else
         on a video slide competes with it for the screen. -->
    <div
      v-if="currentVideoUrl && !mediaFailed"
      data-testid="presentation-video"
      class="w-full flex justify-center mt-8"
    >
      <VideoPlayer
        ref="videoRef"
        chromeless
        :src="currentVideoUrl"
        :key="currentVideoKey"
        @error="onMediaError"
        @autoplay-blocked="onVideoAutoplayBlocked"
        @play="videoBlocked = false"
      />
    </div>

    <!-- Attached audio — zero-size wrapper, occupies no layout space. -->
    <div
      v-if="currentAudioUrl && !mediaFailed"
      data-testid="presentation-audio"
      class="absolute h-0 w-0 overflow-hidden"
    >
      <AudioPlayer
        ref="audioRef"
        chromeless
        :src="currentAudioUrl"
        :loop="props.slide?.slide.audioLoop"
        :key="currentAudioKey"
        @error="onMediaError"
        @autoplay-blocked="onAudioAutoplayBlocked"
        @play="audioBlocked = false"
      />
    </div>

    <!-- Media-unavailable notice — deliberately NOT bound to chrome
         auto-hide; it reports slide state, not navigation affordance. -->
    <p
      v-if="mediaFailed"
      data-testid="presentation-media-unavailable"
      class="absolute bottom-20 left-6 text-xs text-gray-500 leading-[1.4]"
    >
      Media unavailable
    </p>

    <!-- Autoplay-blocked affordances — additionally gated on `interactive`
         (Phase 90) so a non-interactive preview (e.g. the confidence
         monitor) shows none of them. -->
    <button
      v-if="audioBlocked && props.interactive"
      type="button"
      data-testid="presentation-audio-affordance"
      class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-lg bg-indigo-600 hover:bg-indigo-500 px-8 py-4 text-4xl font-semibold text-white"
      @click="audioRef?.play()"
    >
      Tap to play audio
    </button>

    <button
      v-if="videoBlocked && props.interactive"
      type="button"
      data-testid="presentation-video-affordance"
      class="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 rounded-lg bg-indigo-600 hover:bg-indigo-500 px-8 py-4 text-4xl font-semibold text-white"
      @click="videoRef?.play()"
    >
      Tap to play video
    </button>

    <button
      v-if="videoMutedPlaying && props.interactive"
      type="button"
      data-testid="presentation-muted-chip"
      class="absolute bottom-20 right-6 rounded-full bg-amber-900/40 px-4 py-2 text-sm font-medium text-amber-300"
      @click="onUnmuteClick"
    >
      Playing muted — tap to unmute
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import type {
  AssembledSlide,
  Slide,
  LyricSlide,
  CopyrightSlide,
  ScriptureSlide,
  CongregationalSection,
  TextSlide,
  ImageSlide,
  VideoSlide,
} from '@/types/slide'
import { renderFailureSentence } from './slideDisplay'
import AudioPlayer from '../AudioPlayer.vue'
import VideoPlayer from '../VideoPlayer.vue'

/** See ADR-0111 (docs/adr/0111-phase-90-extracted-from-presentationviewer-vue-slidecanvas-o.md) */
const props = defineProps<{
  slide: AssembledSlide | null
  /** Phase 90/94 — when true, ignore the slide's own resolved background
   *  and render black-only (the confidence-monitor contract lands here). */
  suppressBackground?: boolean
  /** Whether the canvas responds to its own autoplay-blocked affordances.
   *  PresentationViewer's existing behavior is the `interactive: true`
   *  (default-on-there) case; a non-interactive preview shows none. */
  interactive?: boolean
}>()

// ── Refs / state ─────────────────────────────────────────────────────────────

const audioRef = ref<InstanceType<typeof AudioPlayer> | null>(null)
const videoRef = ref<InstanceType<typeof VideoPlayer> | null>(null)

// Per-slide degraded-state flags. All reset on every slide change (the
// `watch` below, equivalent to the pre-extraction resetMediaState() call
// inside goToIndex) so one slide's degraded state never leaks onto the next.
const mediaFailed = ref(false)
const audioBlocked = ref(false)
const videoBlocked = ref(false)
const videoMutedPlaying = ref(false)

// ── Computed ─────────────────────────────────────────────────────────────────

/** R080/D-15 — `'pending' | 'failed' | null` for whichever slide is currently
 * on screen. This branch precedes the entire per-kind chain below (ordering
 * is the mechanism, not a filter) so a render-state slide never falls
 * through to a broken image element or stale parsed text. */
const currentRenderState = computed<'pending' | 'failed' | null>(
  () => props.slide?.slide.renderState ?? null,
)

/** Routed through `renderFailureSentence` — the ONE sanctioned path from the
 * raw `renderFailureReason` slug to the DOM (T-42-04), same as SlideCard.vue. */
const currentRenderFailureSentence = computed(() =>
  renderFailureSentence(props.slide?.slide.renderFailureReason),
)

const currentAudioUrl = computed<string | null>(() => props.slide?.slide.audioUrl ?? null)
/**
 * A video slide's own source (D-17/D-18) — video has no bed layer, so this
 * resolves ONLY from the current slide's own `videoSrc` when it IS a video
 * slide. There is nothing else for a video slide to render (see the
 * template), so this is never truthy at the same time as any body-rendering
 * slide kind.
 */
const currentVideoUrl = computed<string | null>(() => {
  const slide = props.slide?.slide
  return slide?.contentKind === 'video' ? (slide as VideoSlide).videoSrc : null
})

/**
 * See .planning/codebase/ARCHITECTURE.md (§ Component & Composable Behavioral Notes (R318) -> src/components/slides/SlideCanvas.vue)
 */
const currentBackgroundUrl = computed<string | null>(() => {
  if (props.slide?.slide.contentKind === 'blackout') return null
  if (props.suppressBackground) return null
  if (currentVideoUrl.value) return null
  return props.slide?.slide.backgroundImageUrl ?? null
})

/** See ADR-0112 (docs/adr/0112-keys-the-videoplayer-instance-on-the-slide-wr-02-so-switchin.md) */
const currentVideoKey = computed(() => `${props.slide?.slide.id ?? ''}:${currentVideoUrl.value ?? ''}`)

/** See ADR-0112 (docs/adr/0112-keys-the-videoplayer-instance-on-the-slide-wr-02-so-switchin.md) */
const currentAudioKey = computed(() => {
  const current = props.slide
  if (current?.audioFromBed && current.groupId) {
    return `group:${current.groupId}:${currentAudioUrl.value ?? ''}`
  }
  return `${current?.slide.id ?? ''}:${currentAudioUrl.value ?? ''}`
})

/**
 * Card content kind, narrowed independently of the raw `contentKind` field —
 * LyricSlide and CopyrightSlide both carry `contentKind: 'lyric'` and are
 * distinguished by shape (`sectionId` only present on LyricSlide).
 */
type CardKind = 'lyric' | 'copyright' | 'scripture' | 'text' | 'image' | 'video' | 'blackout'

function cardKind(slide: Slide): CardKind {
  if (slide.contentKind === 'lyric') {
    return 'sectionId' in slide ? 'lyric' : 'copyright'
  }
  return slide.contentKind as CardKind
}

const slideKind = computed<CardKind | null>(() => (props.slide ? cardKind(props.slide.slide) : null))

/**
 * A scripture slide renders the speaker block only when it actually carries
 * a `section` (38-02: the field is singular — a slide has at most one). A
 * slide marked `readingMode: 'congregational'` but with no `section` degrades
 * to the normal plain-text rendering rather than projecting an empty block.
 */
const isCongregational = computed(() => {
  const slide = props.slide?.slide
  if (!slide || slide.contentKind !== 'scripture') return false
  const scripture = slide as ScriptureSlide
  return scripture.readingMode === 'congregational' && scripture.section !== undefined
})

/**
 * R095: the speaker label text, always rendered as text regardless of
 * colour (FEATURES.md — colour is never the sole signal).
 */
const speakerLabelText = computed(() => {
  const slide = props.slide?.slide
  if (!slide || slide.contentKind !== 'scripture') return ''
  const section = (slide as ScriptureSlide).section
  if (!section) return ''
  if (section.speaker === 'LEADER') return 'Leader:'
  if (section.speaker === 'CONGREGATION') return 'Congregation:'
  return 'All:'
})

/**
 * The speaker line's colour, and ONLY its colour — see the template comment
 * on `presentation-speaker` for why size/weight/casing deliberately stay put.
 * Returned as a class rather than an inline style so the two values are real
 * Tailwind literals the JIT compiler can see.
 */
const speakerColorClass = computed(() => {
  const slide = props.slide?.slide
  if (!slide || slide.contentKind !== 'scripture') return 'text-gray-100'
  const section = (slide as ScriptureSlide).section
  if (!section) return 'text-gray-100'
  if (section.speaker === 'LEADER') return 'text-sky-300'
  if (section.speaker === 'CONGREGATION') return 'text-amber-300'
  return 'text-violet-300'
})

// ── Media driving — imperative play/pause only; the players expose no attribute that triggers unattended playback ──

/** No-op on a slide with no mounted media (optional-chained). */
function pauseCurrentMedia() {
  audioRef.value?.pause()
  videoRef.value?.pause()
}

/**
 * Both play() calls are async and their rejections are already handled
 * inside the players (autoplay-blocked handling lives there) — do not await
 * them here and do not attach a catch that would swallow anything other
 * than the NotAllowedError the players already handle internally.
 */
function playCurrentMedia() {
  void videoRef.value?.play()
  void audioRef.value?.play()
}

/** Every per-slide media state resets on each slide change so one slide's
 * degraded state never leaks onto the next. */
function resetMediaState() {
  mediaFailed.value = false
  audioBlocked.value = false
  videoBlocked.value = false
  videoMutedPlaying.value = false
}

// T-23-08: PresentationViewer drives pause→reset→play around every slide
// change via these exposed handles; degraded-state reset happens internally
// here on every slide-identity change (equivalent to the pre-extraction
// resetMediaState() call inside goToIndex/the slides-length watcher).
watch(
  () => props.slide?.slide.id,
  () => resetMediaState(),
)

defineExpose({
  play: playCurrentMedia,
  pause: pauseCurrentMedia,
})

// ── Media event handlers ──────────────────────────────────────────────────────

/** A media file removed by the Phase 22 two-week retention cleanup is an
 * expected state, not a failure — no console output, no re-fetch, no
 * navigation change. */
function onMediaError() {
  mediaFailed.value = true
}

function onAudioAutoplayBlocked() {
  audioBlocked.value = true
}

/**
 * VideoPlayer emits the same 'autoplay-blocked' event for both the muted-retry
 * success and the hard-block cases (per the locked STATE.md decision) — the
 * two are told apart here by reading the exposed `isMuted` accessor rather
 * than a second event.
 */
function onVideoAutoplayBlocked() {
  const stillMuted = videoRef.value?.isMuted === true
  if (stillMuted) {
    videoMutedPlaying.value = true
    videoBlocked.value = false
  } else {
    videoBlocked.value = true
    videoMutedPlaying.value = false
  }
}

function onUnmuteClick() {
  void videoRef.value?.unmute()
  videoMutedPlaying.value = false
}
</script>

<style scoped>
/* See .planning/codebase/STACK.md (§ Component & Composable Stack Notes (R318) -> src/components/slides/SlideCanvas.vue) */
[data-testid='presentation-body'].text-5xl {
  font-weight: var(--slide-font-weight);
  font-size: calc(3rem * var(--slide-font-scale));
}
[data-testid='presentation-body'].text-6xl {
  font-size: calc(3.75rem * var(--slide-font-scale));
}
[data-testid='presentation-scripture-reference'] {
  font-weight: var(--slide-font-weight);
  font-size: calc(3rem * var(--slide-font-scale));
}
[data-testid='presentation-speaker'] {
  font-weight: var(--slide-font-weight);
  font-size: calc(3rem * var(--slide-font-scale));
}
[data-testid='presentation-congregational-section'] {
  font-weight: var(--slide-font-weight);
  font-size: calc(3rem * var(--slide-font-scale));
}
/* Deliberately NO font-weight override here — the copyright title/authors
   keep their existing font-semibold hierarchy (only the primary font-normal
   body/scripture/speaker/congregational elements above get the weight var). */
[data-testid='presentation-copyright-fine-print'] {
  font-size: calc(0.75rem * var(--slide-font-scale));
}
.presentation-copyright-authors {
  font-size: calc(1.5rem * var(--slide-font-scale));
}
</style>
